### ISSUE TITLE
why use a real marketplace package?

### ISSUE THREAD

**Issue by fooman** [pmetpublic-reader/packagist-test-org#2]
Just to let you know that I am a customer of paradoxlabs/tokenbase and this "test" is affecting real customers.

**Comment by keithbentrup** [comment]
I understand, and I’m sorry for the inconvenience. However, it was a preventative measure. ParadoxLabs now has the namespace and may choose (or not) to mirror the tokenbase package on packagist.org.

Read more about dependency confusion here: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610

**Comment by fooman** [comment]
Yeap instead of using a real package with a real version number one could have just taken `paradoxlabs/non-existing:0.0.1` - combine this with another issue of shared packages going missing on repo.magento.com it's not a good look.

**Comment by keithbentrup** [comment]
Can you tell me more about which missing packages? We're interested in understanding more about when packages are falling through to packagist.org.

**Comment by fooman** [comment]
I have reported a different issue a while ago where repo.magento.com does not add all of the shared packages for customers into their repo.magento.com that should get added.

paradoxlabs/tokenbase is also a shared package associated with paradoxlabs/subscriptions of which I happen to be a customer.

In the past I had access to
paradoxlabs/tokenbase 4.3.4 

Unfortunately I am currently getting
paradoxlabs/tokenbase 4.3.5 (which is this broken package)
and I also no longer have access to 4.3.4.

![image](https://user-images.githubusercontent.com/455508/112564555-60eb0c00-8e40-11eb-8832-47e7600e3d98.png)

**Comment by keithbentrup** [comment]
@fooman I know that you're a long time contributor in the community, so you probably are familiar with the entitlement system. Just in case, here's some info on it: https://community.magento.com/t5/Magento-DevBlog/Magento-Marketplace-Composer-Repository-and-Entitlements/ba-p/61229 This may shed some light on what's happening.

My guesses are that an entitlement associated with your MagID may have expired? Or maybe you have more than one and the access was associated with another? Or maybe there was an update error to your account at repo.magento.com? Or like you said maybe the entitlement was associated with the subscriptions but not the tokenbase package, and/or that changed over time inadvertently.

Unfortunately, I don't have access to verify access for specific accounts, but you should be able to confirm access to packages under your marketplace account. You can also clear your composer cache and now that the tokenbase package at packagist.org has been removed, composer should only see only the ones your current composer credentials provide at repo.magento.com, and that should help you get the right one provided that the account being used has access.

If you do track down a specific cause, please let me know. If people are loosing access to packages when they should not, I will try to bubble this up to the right people. Thank you.

**Comment by fooman** [comment]
I have reported this for separate instances of this affecting customers of my own extensions on marketplace.

It's the first I hear about expiring entitlements (It's a feature I inquired about 5 years ago).

For my issue MAG005528258 should be straight forward as that is the only ordered extension and I still have access to for example:

```
Selected paradoxlabs/tokenbase (4.2.1)
Selected paradoxlabs/tokenbase (4.2.6)
Selected paradoxlabs/tokenbase (4.2.2)
Selected paradoxlabs/tokenbase (4.2.3)
Selected paradoxlabs/tokenbase (4.2.4)
Selected paradoxlabs/tokenbase (4.2.5)
```

**Comment by pmetpublic-reader** [comment]
@fooman moving to community engineering slack for discussion. thank you.
